apiVersion: apps/v1
kind: Deployment
metadata:
  name: platypus-web-pages
  namespace: kqi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platypus-web-pages
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      name: platypus-web-pages
      labels:
        app: platypus-web-pages
      annotations:
        # アップデート時にPod再起動をかけるためのワークアラウンド
        # configmapのみ変更だとPod再起動しないのでannotationを変更させる
        timestamp: "{{ .Release.Time }}"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kqi_node }}
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      containers:
      - name: platypus-web-pages
        image: kamonohashi/web-pages:{{ .Values.image_tag | default .Chart.Version }}
        resources:
          limits:
            cpu: {{ .Values.resources.platypus_web_pages.cpu }}
            memory: {{ .Values.resources.platypus_web_pages.memory }}
          requests:
            cpu: {{ .Values.resources.platypus_web_pages.cpu }}
            memory: {{ .Values.resources.platypus_web_pages.memory }}
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/nginx/conf.d"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: kqi-system
data:
  default.conf: |
    server {
      listen       80 default_server;
      send_timeout 900;
      proxy_connect_timeout 900;
      proxy_read_timeout    900;
      proxy_send_timeout    900;
      location /api {
        proxy_pass http://platypus-web-api.kqi-system.svc.cluster.local:8090;
      }
      location /kamonohashi {
        root /app/;
      }
      location /aquarium {
        root /app/;
      }
      location /ws {
        proxy_pass http://platypus-web-api-ws.kqi-system.svc.cluster.local:8091;
        # WebSocket用の設定
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
      location / {
         # デフォルトはKAMONOHASHI
        return 301 /kamonohashi/;
      }
    }
