- hosts: kube-node
  become: true
  become_method: sudo
  gather_facts: no # ref. https://htnosm.hatenablog.com/entry/2017/07/30/090000
  tasks:
  - name: Add or update nvidia docker Apt signing key, uses whichever key is at the URL
    shell: curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
    ignore_errors: true