# kamonohashiをデプロイするnode
kqi_node: "${KQI_NODE}"
# オブジェクトストレージとしてminioをデプロイするかどうか
minio_deploy: true

appsettings:
  DeployOptions__GpuNodes: "${NODES}"
  DeployOptions__ObjectStorageNode: "${OBJECT_STORAGE}"
  DeployOptions__ObjectStoragePort: "${OBJECT_STORAGE_PORT}"
  DeployOptions__ObjectStorageAccessKey: "${OBJECT_STORAGE_ACCESSKEY}"
  DeployOptions__NfsStorage: "${NFS_STORAGE}"
  DeployOptions__NfsPath: "${NFS_PATH}"
  BackupPostgresTimerOptions__WeeklyTimeSchedule: "Sun=01:00:00"
  BackupPostgresTimerOptions__MaxNumberOfBackupFiles: "1"
#   ActiveDirectoryOptions__Domain: ""
#   ActiveDirectoryOptions__BaseDn: ""
#   ActiveDirectoryOptions__BaseOu: "\"\""
#   ActiveDirectoryOptions__Server: ""

# 各コンテナのリソース割り当て
resources:
  platypus_web_api:
    cpu: 500m
    memory: 1024Mi
  platypus_web_pages:
    cpu: 100m
    memory: 256Mi
  postgres:
    cpu: 500m
    memory: 2048Mi
  minio:
    cpu: 500m
    memory: 512Mi
  nginx:
    cpu: 500m
    memory: 256Mi

# コンテナに指定するプロキシ
# http_proxy:
# https_proxy:
# no_proxy:
