apiVersion: v1
kind: Secret
metadata:
  name: postgres-credential
  namespace: kqi-system
  labels:
    app.kubernetes.io/name: postgres-credential
    app.kubernetes.io/instance: postgres-credential
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: credential
    app.kubernetes.io/part-of: kamonohashi
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  POSTGRES_PASSWORD: "{{ .Values.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credential
  namespace: kqi-system
  labels:
    app.kubernetes.io/name: minio-credential
    app.kubernetes.io/instance: minio-credential
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: credential
    app.kubernetes.io/part-of: kamonohashi
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  MINIO_SECRET_KEY: "{{.Values.storage_secretkey | b64enc}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: platypus-web-api-env-secret
  namespace: kqi-system
  labels:
    app.kubernetes.io/name: web-api-credential
    app.kubernetes.io/instance: web-api-credential
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: credential
    app.kubernetes.io/part-of: kamonohashi
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ printf "Server=postgres;Port=5432;User Id=platypus;Password=%s;Database=platypusdb;Integrated Security=False;Timeout=30" .Values.db_password | b64enc }}
  DeployOptions__Password: "{{.Values.password | b64enc}}"
  DeployOptions__ObjectStorageSecretKey: "{{.Values.storage_secretkey | b64enc}}"
