apiVersion: v1
kind: ServiceAccount
metadata:
  name: platypus
  namespace: kqi-system
  labels:
    app.kubernetes.io/name: playpus
    app.kubernetes.io/instance: platypus
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: web-api-service-account
    app.kubernetes.io/part-of: kamonohashi
    app.kubernetes.io/managed-by: helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platypus
  labels:
    app.kubernetes.io/name: playpus
    app.kubernetes.io/instance: platypus
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: platypus-service-account-role-bind
    app.kubernetes.io/part-of: kamonohashi
    app.kubernetes.io/managed-by: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: platypus
    namespace: kqi-system
---
