apiVersion: v1
kind: ServiceAccount
metadata:
  name: platypus
  namespace: kqi-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: platypus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: platypus
    namespace: kqi-system
---